### ISSUE TITLE
Meta DRP prevents uploading

### ISSUE THREAD

**Issue by NitroBAY** [cloudinary/cloudinary_js#100]
Hello,
I use $('#upload-img').unsigned_cloudinary_upload(), when I add head <meta http-equiv="Accept-CH" content="DPR, Viewport-Width, Width"> I have Fetch API cannot load https://api.cloudinary.com/v1_1/<cloudname>/auto/upload. Request header field dpr is not allowed by Access-Control-Allow-Headers in preflight response.
I use a JS framework called Meteor, even tough it doesn't seem related.
So #99 and #100 makes impossible to make images responsives for now !!!

**Comment by nadavofi** [comment]
Hi, thanks for sharing this issue.
We will make sure to whitelist these headers on the Access-Control settings.
This should be deployed by the beginning of next week.

**Comment by NitroBAY** [comment]
Thanks. I'm surprised none already noticed that, I taught I missed something.

**Comment by MaorGariv** [comment]
Hi,

The fix was deployed:)

The headers are now added to Access-Control if given.
Thanks for pointing us to the issue.

**Comment by NitroBAY** [comment]
The problem is still here : `Fetch API cannot load https://api.cloudinary.com/v1_1/dnr98e5qo/auto/upload. Request header field dpr is not allowed by Access-Control-Allow-Headers in preflight response.`

**Comment by MaorGariv** [comment]
Hi,
The problem should be fixed now. Can you please try again?

Let me know of any updates.

**Comment by NitroBAY** [comment]
No bugs any more on upload. I think it's solved, I will just check a lil more before close.

**Comment by NitroBAY** [comment]
It seems to work now, thanks !

**Comment by MaorGariv** [comment]
Great.. Thanks for the update:)
